onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top/DUT/CLK
add wave -noupdate /top/DUT/nRST
add wave -noupdate /top/DUT/valid_in
add wave -noupdate /top/DUT/op_in
add wave -noupdate /top/DUT/is_imm_in
add wave -noupdate /top/DUT/imm_in
add wave -noupdate /top/DUT/A_unneeded_in
add wave -noupdate /top/DUT/A_forward_in
add wave -noupdate /top/DUT/A_bank_in
add wave -noupdate /top/DUT/B_forward_in
add wave -noupdate /top/DUT/B_bank_in
add wave -noupdate /top/DUT/dest_PR_in
add wave -noupdate /top/DUT/ROB_index_in
add wave -noupdate /top/DUT/A_reg_read_valid_in
add wave -noupdate /top/DUT/B_reg_read_valid_in
add wave -noupdate /top/DUT/reg_read_data_by_bank_in
add wave -noupdate /top/DUT/forward_data_by_bank_in
add wave -noupdate /top/DUT/ready_out
add wave -noupdate /top/DUT/WB_valid_out
add wave -noupdate /top/DUT/WB_data_out
add wave -noupdate /top/DUT/WB_PR_out
add wave -noupdate /top/DUT/WB_ROB_index_out
add wave -noupdate /top/DUT/valid_OC
add wave -noupdate /top/DUT/op_OC
add wave -noupdate /top/DUT/is_imm_OC
add wave -noupdate /top/DUT/imm_OC
add wave -noupdate /top/DUT/A_unneeded_OC
add wave -noupdate /top/DUT/A_saved_OC
add wave -noupdate /top/DUT/A_forward_OC
add wave -noupdate /top/DUT/A_bank_OC
add wave -noupdate /top/DUT/B_saved_OC
add wave -noupdate /top/DUT/B_forward_OC
add wave -noupdate /top/DUT/B_bank_OC
add wave -noupdate /top/DUT/dest_PR_OC
add wave -noupdate /top/DUT/ROB_index_OC
add wave -noupdate /top/DUT/launch_ready_OC
add wave -noupdate /top/DUT/stall_OC
add wave -noupdate /top/DUT/next_valid_EX
add wave -noupdate /top/DUT/next_op_EX
add wave -noupdate /top/DUT/next_A_EX
add wave -noupdate /top/DUT/next_B_EX
add wave -noupdate /top/DUT/next_dest_PR_EX
add wave -noupdate /top/DUT/next_ROB_index_EX
add wave -noupdate /top/DUT/valid_EX
add wave -noupdate /top/DUT/op_EX
add wave -noupdate /top/DUT/A_EX
add wave -noupdate /top/DUT/B_EX
add wave -noupdate /top/DUT/dest_PR_EX
add wave -noupdate /top/DUT/ROB_index_EX
add wave -noupdate /top/DUT/next_WB_valid_out
add wave -noupdate /top/DUT/next_WB_data_out
add wave -noupdate /top/DUT/next_WB_PR_out
add wave -noupdate /top/DUT/next_WB_ROB_index_out
add wave -noupdate /top/DUT/CLK
add wave -noupdate /top/DUT/nRST
add wave -noupdate /top/DUT/valid_in
add wave -noupdate /top/DUT/op_in
add wave -noupdate /top/DUT/is_imm_in
add wave -noupdate /top/DUT/imm_in
add wave -noupdate /top/DUT/A_unneeded_in
add wave -noupdate /top/DUT/A_forward_in
add wave -noupdate /top/DUT/A_bank_in
add wave -noupdate /top/DUT/B_forward_in
add wave -noupdate /top/DUT/B_bank_in
add wave -noupdate /top/DUT/dest_PR_in
add wave -noupdate /top/DUT/ROB_index_in
add wave -noupdate /top/DUT/A_reg_read_valid_in
add wave -noupdate /top/DUT/B_reg_read_valid_in
add wave -noupdate /top/DUT/reg_read_data_by_bank_in
add wave -noupdate /top/DUT/forward_data_by_bank_in
add wave -noupdate /top/DUT/ready_out
add wave -noupdate /top/DUT/WB_valid_out
add wave -noupdate /top/DUT/WB_data_out
add wave -noupdate /top/DUT/WB_PR_out
add wave -noupdate /top/DUT/WB_ROB_index_out
add wave -noupdate /top/DUT/valid_OC
add wave -noupdate /top/DUT/op_OC
add wave -noupdate /top/DUT/is_imm_OC
add wave -noupdate /top/DUT/imm_OC
add wave -noupdate /top/DUT/A_unneeded_OC
add wave -noupdate /top/DUT/A_saved_OC
add wave -noupdate /top/DUT/A_forward_OC
add wave -noupdate /top/DUT/A_bank_OC
add wave -noupdate /top/DUT/B_saved_OC
add wave -noupdate /top/DUT/B_forward_OC
add wave -noupdate /top/DUT/B_bank_OC
add wave -noupdate /top/DUT/dest_PR_OC
add wave -noupdate /top/DUT/ROB_index_OC
add wave -noupdate /top/DUT/launch_ready_OC
add wave -noupdate /top/DUT/stall_OC
add wave -noupdate /top/DUT/next_valid_EX
add wave -noupdate /top/DUT/next_op_EX
add wave -noupdate /top/DUT/next_A_EX
add wave -noupdate /top/DUT/next_B_EX
add wave -noupdate /top/DUT/next_dest_PR_EX
add wave -noupdate /top/DUT/next_ROB_index_EX
add wave -noupdate /top/DUT/valid_EX
add wave -noupdate /top/DUT/op_EX
add wave -noupdate /top/DUT/A_EX
add wave -noupdate /top/DUT/B_EX
add wave -noupdate /top/DUT/dest_PR_EX
add wave -noupdate /top/DUT/ROB_index_EX
add wave -noupdate /top/DUT/next_WB_valid_out
add wave -noupdate /top/DUT/next_WB_data_out
add wave -noupdate /top/DUT/next_WB_PR_out
add wave -noupdate /top/DUT/next_WB_ROB_index_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {374 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
